### PR TITLE
Add Engine function for counting Entity components and Systems

### PR DESCRIPTION
**Pull request by hewills**
Add two Engine functions to count Entities with given component and
existing Systems. Add test specs for functions.

### CODE REVIEW

**Comment by hewills** [comment]
I needed a component count function for my game, and thought it may be useful for others. There are other ways to obtain it, but this may be worth adding. Thanks

**Comment by Nukesor** [comment]
The getEntityCount function is actually a good idea and i can think about a few scenarios, where this could be helpful.
But I don't know what the getSystemCount function is for. It would be nice, if you could explain why you need this, before we add it to our library.

Thanks for contributing!

**Comment by hewills** [comment]
Nope. The getEntityCount is the only function I've truly needed so far. I can't think of a good reason for SystemCount at the moment either. I just threw it in in case there was one. Should I go ahead and remove it?

**Comment by Nukesor** [comment]
Yep, that would be great :)!
I'll merge the PR afterwards.

**Comment by hewills** [comment]
Great, I removed the systemCount function from the PR. Let me know if any other changes are needed. And thanks for the great framework, it's been very helpful!

**Comment by Nukesor** [comment]
LGTM, I'll merge it :+1: 
Thanks for contributing

**Pull request merged**
