### PR TITLE
Refactor for container-based infrastructure

### PR DESCRIPTION
**Pull request by Luminess**
- Use hererocks to install LuaJIT and LuaRocks. Removes the need for sudo.
- Moved testing tool installation to the before_script stage.
- Build the rock on the install stage. The install stage of the build lifecycle is typically used for building/installing the project itself and not the testing suite.
- Cache LuaJIT's build and LuaRocks's rocks builds.
- Decreased maximum git cloning depth from the default of 50 commits to 4 commits to decrease clone size. The default value is only useful if we're performing git operations during the build.

Use LuaJIT v2.0.3 to match the latest Love2D's Lua runtime.

CI builds should now take ~17 seconds from the commit being picked up by Travis to build finish (including VM startup time) instead of ~40 seconds. Note that the elapsed time reported by Travis doesn't factor in VM startup time.

### CODE REVIEW

**Comment by Luminess** [comment]
fixes #44

**Comment by raffomania** [comment]
Thanks for this PR. There are two things we'd like to see fixed before merging this:

- Please rename the `l` directory to something more descriptive, like `lua_installation`, `lua_directory` or something along that.
- How will this work if there is a new minor luajit version, like 2.1.0? The hererocks readme states that the installation directory should be deleted before installing a new minor version. Our suggestion would be to just remove the cache directive, as travis builds really are not timing critical and the few extra seconds for installing lua are not a problem.

**Comment by Luminess** [comment]
Both points handled in the first 2 commits after your comment. Just attempting (and failing miserably) to squash the commits at the moment.

**Comment by Luminess** [comment]
Both points handled in the last commit.

**Comment by raffomania** [comment]
Alright, I'm merging this, thanks!

**Pull request merged**
