### PR TITLE
Added System.onRemoveEntity callback

### PR DESCRIPTION
**Pull request by Erasio**
Users can now add onRemoveEntity to their System.

Changed componentRemoved() to also use removeEntity to receive the callback whenever an entity is removed.

### CODE REVIEW

**Comment by raffomania** [comment]
makes sense, can you make sure the tests succeed?

**Comment by Erasio** [comment]
Working on adding tests for a bunch for things currently and fixing that test.

Also fyi.
I've started a alternative version named HooECS for a few reasons.

1. Adding a few features I find handy. Such as activating / deactivating entities (remove from / add to systems without removing from engine), event responses for whether it's been used or not being the most noteworthy. And the syntactic sugar of replacing 'require("lovetoys.lovetoys")' with 'require("HooECS")'. 

2. A thing I hear quite a bit is that googling lovetoys at uni and such is uncomfortable in a few scenarios.

Today I plan on setting up all tests and (hopefully) fix everything.

If you want I can submit the full pullrequests for everything once I find everything to be stable. Though I will keep maintaining my version over at https://github.com/hooodini/HooECS for the naming reasons.

Keeping you referenced at the top of the readme and maintaining the license. 

Thanks for everything!

**Comment by Erasio** [comment]
Alright. Fixed it by not going through :removeEntity but adding the callbacks everywhere necessary. 

Also added the index / category to both callbacks. Not sure if that's interesting. But it's there at basically no effort or runtime downsides.

**Comment by Nukesor** [comment]
Hey @Erasio,
Sorry for not answering for such a long time.
We just decided to take a look at the Lövetoys again, since we really don't want to orphan this project.

Right now we are refactoring parts of the Lovetoys and are thereby renaming stuff, updating docs and rewriting some ugly lines of code and logic.

Regarding your proposed changes:

What exactly do you mean by event responses?
Usually deactivating and reactivating entities is done by adding/removing Components, since you don't always want to activate/deactivate an entity for all systems.
What kind of use cases do you have for deactivating entities for all systems, maybe this could help us understand the problem behind this.

In general we would be happy to review and accept some PR's from you :)

**Comment by Nukesor** [comment]
Another thing:
There actually was a bug in your proposed code.
On component removal on a System with normal requirements (no groups) the onRemoveEntity Callback has been called twice.
We're fixing that in the course of the current refactoring process :).
Your PR will still be merged :+1:

**Pull request merged**
