### PR TITLE
Allow lovetoys to be used with any class library

### PR DESCRIPTION
**Pull request by rosshadden**
I added and used some accessor methods instead of accessing/changing properties directly.  This lets people use lovetoys with any arbitrary class framework, rather than forcing them to use Middleclass.  Yes, technically calling a function is slower than accessing a property directly, but this is quite minimal, and the ends justify the means.

I made these changes so that I could use it with the class framework in Moonscript, and it has been working well.

### CODE REVIEW

**Comment by raffomania** [comment]
This looks interesting. A quick look into the moonscript reference didn't show me how it's class system uses getters and setters - the generated code seems to use `self.foo = 'bar'` assignments. Could you provide a little context?
Thanks!

**Comment by rosshadden** [comment]
Yeah, of course.  Take a look at [this reddit post](https://www.reddit.com/r/moonscript/comments/4xc0sf/interoperability_with_middleclass/) I made about it.

The tl;dr is I have an instance of an arbitrary class (in this case Moonscript, but could be anything), with a `self.proxy` object set to the original class.  So `self.proxy == Entity()`.  And then for each of the methods on `Entity`, a wrapper method is created that calls the same method on `self.proxy`.

Using that setup, my `Entity` class has `add`, `set`, `getComponents`, etc. methods, which are all defined automatically, and call `self.proxy.add(self.proxy, ...)`, etc.

**Comment by rosshadden** [comment]
Sorry I linked you to moonscript syntax.  I... ugh.  I hate a lot of parts of it.  I have always hated CoffeScript, Ruby, and all of these kinds of languages.  But until someone makes something like Moonscript that looks a lot less stupid, I am happy with it.

Once I got over hating the syntax I really like just about everything else about it, all the other conveniences it adds.

**Comment by raffomania** [comment]
All right, I think I get what you're doing. Correct me if I'm wrong, but can't you simply proxy field accesses too by using a metatable with an `__index` function?

**Comment by rosshadden** [comment]
Maybe, but I just tried for quite a long time and couldn't get it working doing that.

I know in some other code ecosystems it is good practice to use accessors internally if they exist---it makes for an easily-extendable and scalable API.  I think that even if I could get what you suggested working, I would still think the changes in this PR are good ones.  What do you think?

**Comment by rosshadden** [comment]
By the way, this also lets systems do things when toggled.  With the latest commit, things extending from `System` can override the `toggleActive` or `setActive` methods, which is very useful.  This is true for people using Middleclass, too, which is probably close to 99% of your audience.

**Pull request merged**
